### ISSUE TITLE
add a method to exclude certain project types in search sync

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-policy#100]
### Scenario:
some projects need to never make it into search.  for example, we have project_types that are propriety, and we would like them never to appear in a search index.

### Expected Result:
add a command line option to exclude specific project types.
<search_sync> --exclude-project-types property,test

**Comment by dmlb2000** [comment]
The command line options are kinda limiting, if you want by attribute would something like the following work?

```
--exclude=<obj>.<attr>=<value>
```

This is also limiting as you can't do ranges over dates... not sure how to incorporate that feature.

**Comment by karcaw** [comment]
yes, I think that would work fine.
