### ISSUE TITLE
All user relationships need keyword field of type keyword

### ISSUE THREAD

**Issue by plithnar** [pacifica/pacifica-policy#108]
### Pacifica Policy version
Version 0.70

### Scenario:
Attempting to build facets off of the users.member_of.keyword field on the projects document type. Since the field is of type="text", this operation is not allowed, but this would be allowed if the field is type="keyword"

### Steps to Reproduce:
Perform a post request to https://esapi.my.emsl.pnl.gov/_search with the following JSON body in postman.
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "type": "projects"
          }
        },
        {
          "script": {
            "script": "doc['transaction_ids'].length > 0"
          }
        }
      ]
    }
  },
  "aggs": {
    "project_members3": {
      "filter": {
        "match_all": {}
      },
      "aggs": {
        "users.member_of.keyword": {
          "terms": {
            "field": "users.member_of.keyword",
            "size": 10
          }
        },
        "users.member_of.keyword_count": {
          "cardinality": {
            "field": "users.member_of.keyword"
          }
        }
      }
    }
  },
  "size": 15
}

### Expected Result:
Expected result is 15 projects returned and an aggregation filter on user name (users.member_of.keyword)

### Actual Result:
400 Error returned from the endpoint with the following error:
"root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [users.member_of.keyword] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "pacifica_elastic_16_07_2019",
                "node": "9oGrlJQlSD-Whpmcjm7ksA",
                "reason": {
                    "type": "illegal_argument_exception",
                    "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [users.member_of.keyword] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."
                }
            }
        ]

**Comment by dmlb2000** [comment]
@plithnar This bug doesn't belong here, could you please move it to https://github.com/pacifica/pacifica-elasticsearch?
