### ISSUE TITLE
Add Numeric field for count of Transaction Ids [Improvement]

### ISSUE THREAD

**Issue by plithnar** [pacifica/pacifica-policy#109]
On the Projects document, it would be helpful to have a numeric field that holds the number of transaction ids. This would allow the ability to have a numeric refinement filter based on this field and drive discovery of projects based on this aspect.

**Comment by dmlb2000** [comment]
@plithnar This bug doesn't belong here anymore, could you please move it to https://github.com/pacifica/pacifica-elasticsearch?
