### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by casey-pnnl** [pacifica/pacifica-policy#16]
### Pacifica Policy version
uses pacifica-policy master branch as of 2017-06-14

### Pacifica Core Software versions
Also uses pacifica-metadata master branch as of 2017-06-14

### Platform Details
CentOS Linux release 7.3.1611 (Core)

### Scenario:
Unicode Character problem encountered when attempting to retrieve the Unicode character u'\xa0' (or \u00a0) from pacifica-policy. The character was inserted into pacifica-metadata as the display_name of instruments. 

### Steps to Reproduce:
Insert an instrument into pacifica-metadata with the special unicode character in the display_name. May also require some additional metadata records for proposal, proposal-instrument, etc. On the core server (where pacifica-policy is located in this case), run the following: 
    `curl localhost:8181/status/instrument/by_proposal_id/68158`

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
According to Dave Brown, this should be doable in the current version of pacifica-policy. The expected result is for This should return the json of the instrument records for the proposal '68158'.

Example output snipped for readability:
`{"total_count": 2, "items": [{"active": "Y", "text": "All Available Instruments for Proposal 68158", "id": -1, "name": "All Instruments"}, {"active": "Y", "text": "Instrument 10004, "id": "10004", "name": "Sigma 2"}], "incomplete_results": false}`

### Actual Result:
```
[root@core ~]# curl localhost:8181/status/instrument/by_proposal_id/68158
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.<br />In addition, the custom error page failed:
<br />TypeError: read() takes at most 1 argument (2 given)
</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/opt/policy/virtualenv/lib64/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/policy/virtualenv/lib64/python2.7/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/policy/virtualenv/lib64/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/policy/virtualenv/lib64/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "./policy/__init__.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "./policy/status/instrument/by_proposal_id.py", line 52, in GET
    'text': 'Instrument {0}: {1}'.format(inst_id, info.get('display_name')),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 3: ordinal not in range(128)
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 10.2.2</a>
      </span>
    </div>
    </body>
</html>
[root@core ~]#
```

**Comment by dmlb2000** [comment]
This should be fixed by #17
