### ISSUE TITLE
asserts cause master assertion deadlock.

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-policy#95]
we have seen times when all of the worker threads of search_sync.py hit this assertion:

https://github.com/pacifica/pacifica-policy/blob/c7e0b89e85096665f2f587ed520923fb2708fe9c/pacifica/policy/search/base.py#L57

and then nothing else happens.  Please fix things so that the assertion doesn't just leave the master thread hung waiting for workers to finish that is no longer doing anything.

**Comment by dmlb2000** [comment]
This is a won't fix the elasticsearch code has been moved to https://github.com/pacifica/pacifica-elasticsearch.git
