### ISSUE TITLE
Rendering every transaction for a science theme is disastrous for a search_sync

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-policy#98]
When a full set of projects is rendered for elastic search, the setting on this line:

https://github.com/pacifica/pacifica-policy/blob/c7e0b89e85096665f2f587ed520923fb2708fe9c/pacifica/policy/search_render.py#L43

cause every project, to render every transaction in the science theme for the project.  this makes project search sync horribly slow.

changing the third parameter to False on the above line alleviates this problem.

How should this really be fixed?

**Comment by dmlb2000** [comment]
I think you are right, I thought this was a slightly different issue related to #96. 

I'm going to have to close this anyway, rendering every transaction for a science theme is required to make elasticsearch index the science theme correctly. If the science theme has a lot of transactions, I think that's how it's suppose to behave.
